--CRIAR TABELA CLIENTES

CREATE TABLE HR.CLIENTES 
    ( 
     CLIENTE_ID NUMBER , 
     NOME       VARCHAR2 (50) , 
     EMAIL      VARCHAR2 (50) 
    ) 
    TABLESPACE USERS 
    LOGGING 
;

ALTER TABLE HR.CLIENTES 
    ADD PRIMARY KEY ( CLIENTE_ID ) 
    USING INDEX LOGGING ;


--CRIAR TABELA PRODUTOS

CREATE TABLE HR.PRODUTOS 
    ( 
     PRODUTO_ID NUMBER , 
     NOME       VARCHAR2 (50) , 
     PRECO      NUMBER (15,2) 
    ) 
    TABLESPACE USERS 
    LOGGING 
;

ALTER TABLE HR.PRODUTOS 
    ADD PRIMARY KEY ( PRODUTO_ID ) 
    USING INDEX LOGGING ;

--CRIAR TABELA PEDIDOS

CREATE TABLE HR.PEDIDOS 
    ( 
     PEDIDO_ID    NUMBER DEFAULT "HR"."PEDIDOS_SEQ"."NEXTVAL" , 
     CLIENTE_ID   NUMBER , 
     DATA_PEDIDO  DATE , 
     TOTAL_PEDIDO NUMBER (15,3) 
    ) 
    TABLESPACE USERS 
    LOGGING 
;

ALTER TABLE HR.PEDIDOS 
    ADD PRIMARY KEY ( PEDIDO_ID ) 
    USING INDEX LOGGING ;

ALTER TABLE HR.PEDIDOS 
    ADD CONSTRAINT FK_PEDIDOS_CLIENTES FOREIGN KEY 
    ( 
     CLIENTE_ID
    ) 
    REFERENCES HR.CLIENTES ( CLIENTE_ID ) 
    NOT DEFERRABLE 
;

--CRIAR SEQUENCIAL "PEDIDOS_SEQ"

CREATE SEQUENCE pedidos_seq START WITH 1 INCREMENT BY 1;

-- CRIAR TABELA ITENS_PEDIDO

CREATE TABLE HR.ITENS_PEDIDO 
    ( 
     ITEM_ID    NUMBER , 
     PEDIDO_ID  NUMBER , 
     PRODUTO_ID NUMBER , 
     QUANTIDADE NUMBER 
    ) 
    TABLESPACE USERS 
    LOGGING 
;

ALTER TABLE HR.ITENS_PEDIDO 
    ADD PRIMARY KEY ( ITEM_ID ) 
    USING INDEX LOGGING ;

ALTER TABLE HR.ITENS_PEDIDO 
    ADD CONSTRAINT FK_ITENS_PEDIDO_PEDIDOS FOREIGN KEY 
    ( 
     PEDIDO_ID
    ) 
    REFERENCES HR.PEDIDOS ( PEDIDO_ID ) 
    NOT DEFERRABLE 
;

ALTER TABLE HR.ITENS_PEDIDO 
    ADD CONSTRAINT FK_ITENS_PEDIDO_PRODUTOS FOREIGN KEY 
    ( 
     PRODUTO_ID
    ) 
    REFERENCES HR.PRODUTOS ( PRODUTO_ID ) 
    NOT DEFERRABLE 
;

--CRIAR SEQUENCIAL 

CREATE SEQUENCE itens_pedido_seq START WITH 1 INCREMENT BY 1;